[tools]
go = "1.26.0"
goreleaser = "2.13.3"
"golangci-lint" = "2.9.0"

[tasks.build]
run = "go build ./cmd/demod/"

[tasks.test]
run = "go test ./..."

[tasks.lint]
run = "golangci-lint run"

[tasks.release-check]
run = "goreleaser check"

[tasks.release-snapshot]
run = "goreleaser release --snapshot --clean"
